name: graphes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation
      run: sudo apt-get install -y graphviz
    - name: Check Out repository code
      uses: actions/checkout@v3
    - name: Lancement graphviz
      run: ./graphiz2.sh
    - name: Upload du resultat
      uses: actions/upload-artifact@v4
      with:
        name: banane
        path: g*.svg
